# Generated by Django 5.2 on 2025-04-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_project_alter_comment_created_by_task_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
