# Generated by Django 5.2 on 2025-04-17 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_worker_must_change_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="must_change_password",
        ),
        migrations.AddField(
            model_name="project",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
